############################# English ############################
[en]
languageCode  = "en-us"
languageName = "En"
title = "Champion AfricTivistes of governance and democracy"
contentDir = "content/english"
weight = 1

############################# French ############################
[fr]
languageCode  = "fr"
languageName = "Fr"
title = "Champion AfricTivistes de la gouvernance et de la démocratie "
contentDir = "content/french"
weight = 2
    