# Navbar Menus
[[nav]]
  name    = "Home"
  url     = "/en"
  weight  = 1
[[nav]]
  name    = "About"
  url     = "en/about"
  weight  = 2
[[nav]]
  name    = "Newsroom"
  url     = "en/newsroom"
  weight  = 3
[[nav]]
  name    = "Jury"
  url     = "en/comitejury"
  weight  = 4
[[nav]]
  name    = "Champions"
  url     = "en/vote"
  weight  = 5