# Site Params
logo = "images/logo.png"
dateFormat = "26 FEB 1994"
# Meta data
description = "Champion AfricTivistes de la gouvernance et de la démocratie  #AfricTivistes"
author = "AfricTivistes"
# Google Analitycs
googleAnalitycsID = "G-6S69LEB4Q1"

# Navbar Action Button
[navAction]
status  = true
name    = "Nominate Someone"
url     = "contact"
