# Banner Section
[banner]
enable                = true
background_image      = "/images/cadeg.png"
heading               = ""
tagline               = ""
primary_button        = "About"
primary_button_url    = "about"
secondary_button      = "Vote"
secondary_button_url  = "vote"

[call_to_action]
enable              = true
background_image    = "images/backgrounds/cta-background.jpg"
title               = "Be an actor! Vote for someone"
primary_button      = "Vote"
primary_button_url  = "vote"

[newsroom]
enable    = true
title     = "NEWSROOM"
subtitle  = "Keep up with all the latest news on the AfricTivistes Champion of Governance and Democracy"

[press]
enable    = true
title     = "LA PRESSE EN PARLE"
subtitle  = ""

[comitejury]
enable    = true
title     = "Panel of Judge"
subtitle  = "The jury is composed of members of the advisory committee and the selection committee. These two groups bring together experts and actors from African civil society."


[footer]
# Footer Contact Info
[footer.contactInfo]
    title   = "Informations de contact"
    subtitle = "This activity is co-financed by the European Union. It's content is the sole responsability of the Charter Project Africa and does not necessarily reflect the opinions of the European Union"
    address = "AfricTivistes, BP : 19968 (Sénégal)"
    phone   = "(+221) 33 837 51 24"
    email   = "info@africtivistes.org"
    # Footer Sitemap
    [footer.sitemap]
    title   = "Sitemap"
    [[footer.sitemap.link]]
        name = "Home"
        url = "/en"
    [[footer.sitemap.link]]
        name = "About"
        url  = "en/about"
    [[footer.sitemap.link]]
        name = "News"
        url  = "en/newsroom"
    [[footer.sitemap.link]]
        name = "Vote"
        url  = "en/vote"
    # Footer Social Media
    [footer.social]
    title   = "Social Media"
    [[footer.social.link]]
        name = "Twitter"
        url  = "https://twitter.com/AFRICTIVISTES"
    [[footer.social.link]]
        name = "Facebook"
        url  = "https://www.facebook.com/africtivistes/"
    # Footer Service
    [footer.service]
    title       = ""
    description = ""